#!/bin/bash
cat /dev/random | dd if=/dev/stdin bs=1 count=128 iflag=fullblock 2>/dev/null | base64 -i |  sed -e ':a;N;$!ba;s/\n//g' -e 's/[^a-zA-Z0-9]//g'
# Thanks to ultramancool for helping me silence dd .
# Thanks to LazyWolf for letting use part of his script.
# http://forum.bittorrent.com/topic/21802-generate-very-secure-and-random-btsync-secrete-in-linux/